### ISSUE TITLE
Not an issue, a question: data-role="tagsinput" and just that?

### ISSUE THREAD

**Issue by rubenlpz** [aamdani/bootstrap-tagsinput#1]
A question: After installing the package is just necesary to add to your inputs in html:  data-role="tagsinput"?  I added that and its not working =/

**Comment by rubenlpz** [comment]
It didn't works until I add a command in Tempate.onRedered:

```
Template.myTemplate.onRendered(function(){
    $('#tagsInput').tagsinput();
});
```

and in html added and ID for the input:

`<input id=tagsInput type="text" data-role"tagsinput">`

**Comment by aamdani** [comment]
I appreciate the documentation provided here. If anyone else encounters this issue, please refer to the above comment by @rubenlpz.
